name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-e35a1671df25be5c849ca8e31-nonprodbucket-1qt1udt1e40k7
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
            //echo 'copying files to s3 bucket'
            //aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
